### ISSUE TITLE
error when i killed the monster 

### ISSUE THREAD

**Issue by tienppham7** [raphaelkieling/addon-anki-rpg#30]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.12.6 PyQt 5.12.3
Platform: Windows 7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2022-07-16 09:17:48

Caught exception:
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Anki2\addons21\addon-anki-rpg-master\ui.py", line 114, in daily_check
    self.player.receive_loot(DailyLoot().getLoot())
  File "C:\Users\ADMIN\AppData\Roaming\Anki2\addons21\addon-anki-rpg-master\player.py", line 264, in receive_loot
    self.emit("change")
  File "C:\Users\ADMIN\AppData\Roaming\Anki2\addons21\addon-anki-rpg-master\observer.py", line 14, in emit
    obs["fn"](self, data)
  File "C:\Users\ADMIN\AppData\Roaming\Anki2\addons21\addon-anki-rpg-master\ui.py", line 100, in <lambda>
    self.player.subscribe("change", lambda x, y: self.update_player())
  File "C:\Users\ADMIN\AppData\Roaming\Anki2\addons21\addon-anki-rpg-master\ui.py", line 360, in update_player
    self.populate_inventory()
  File "C:\Users\ADMIN\AppData\Roaming\Anki2\addons21\addon-anki-rpg-master\ui.py", line 262, in populate_inventory
    invetory_slot = self.inventory_slots[item.position]
IndexError: list index out of range

**Comment by raphaelkieling** [comment]
Sorry for it, very happy to see that someone Is trying to use it, i put it on pause for some months to focus on my current job. I will keep updating the project during my free time. Thanks to let me know 😄
